### ISSUE TITLE
It  fails to compile when add the sdk 'com.medallia.digital.mobilesdk:android-sdk:3.9.1'

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/Taskr-Sample-Intune-Android-App#23]
I create  a demo and  then add the  the sdk 'com.medallia.digital.mobilesdk:android-sdk:3.9.1', but it failed to compile
There is the demo link:https://github.com/Nash123-start/ApplicationTest

and the error is :

Mamification failed: onMAMCreate (Landroid/os/Bundle;)V in com.medallia.digital.mobilesdk.c0: conflict: int and androidx.appcompat.app.AppCompatActivity
javassist.CannotCompileException: onMAMCreate (Landroid/os/Bundle;)V in com.medallia.digital.mobilesdk.c0: conflict: int and androidx.appcompat.app.AppCompatActivity
at javassist.expr.ExprEditor.doit(ExprEditor.java:122)
at javassist.CtClassType.instrument(CtClassType.java:1554)
at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClass(BuildTimeMamifier.java:454)
at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClass(BuildTimeMamifier.java:391)
at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClasses(BuildTimeMamifier.java:195)
at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:107)
at com.microsoft.intune.mam.MamifyTransformBase.transform(MamifyTransformBase.java:185)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
at com.android.build.gradle.internal.profile.NoOpAnalyticsService.recordBlock(NoOpAnalyticsService.kt:72)
at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:242)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
at

**Comment by bannus** [comment]
Hi @Nash123-start, if you're still having this issue, can you re-post it in [ms-intune-app-sdk-android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) and fill out the bug template there? This repository is for issues specific to the Taskr sample app.
