### ISSUE TITLE
Caused by: java.lang.ClassCastException: com.microsoft.intune.mam.client.view.PolicyWindowManager cannot be cast to android.view.WindowManagerImpl

### ISSUE THREAD

**Issue by akashm002** [msintuneappsdk/Taskr-Sample-Intune-Android-App#25]
Im integrating intune for our app in that we are also using chinalwb/Android-Rich-text-Editor (https://github.com/chinalwb/Android-Rich-text-Editor)....but getting following crash

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ms.portal/com.ms.engage.ui.ShareScreen}: java.lang.ClassCastException: com.microsoft.intune.mam.client.view.PolicyWindowManager cannot be cast to android.view.WindowManagerImpl
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassCastException: com.microsoft.intune.mam.client.view.PolicyWindowManager cannot be cast to android.view.WindowManagerImpl
        at android.view.Window.setWindowManager(Window.java:822)
        at android.view.Window.setWindowManager(Window.java:804)
        at android.app.Dialog.<init>(Dialog.java:207)
        at android.app.Dialog.<init>(Dialog.java:181)
        at com.microsoft.intune.mam.client.app.MAMDialog.<init>(MAMDialog.java:37)
        at androidx.appcompat.app.AppCompatDialog.<init>(AppCompatDialog.java:57)
        at androidx.appcompat.app.AlertDialog.<init>(AlertDialog.java:98)
        at androidx.appcompat.app.AlertDialog.<init>(AlertDialog.java:88)
        at com.chinalwb.are.styles.windows.AlignmentPickerDialog.<init>(AlignmentPickerDialog.java:24)
        at com.chinalwb.are.styles.toolitems.styles.ARE_Style_Alignment.<init>(ARE_Style_Alignment.java:51)
        at com.chinalwb.are.styles.toolitems.ARE_ToolItem_AlignmentLeft.getStyle(ARE_ToolItem_AlignmentLeft.java:56)
        at com.chinalwb.are.AREditText.setToolbar(AREditText.java:200)
        at com.ms.engage.ui.ShareScreen.setupRichTextToolbar(ShareScreen.java:925)
        at com.ms.engage.ui.ShareScreen.initViews(ShareScreen.java:824)
        at com.ms.engage.ui.ShareScreen.onMAMCreate(ShareScreen.java:486)

**Comment by bannus** [comment]
Hi @akashm002, if you're still having this issue, can you re-post it in [ms-intune-app-sdk-android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android)? This repository is for issues specific to the Taskr sample app.
